[[metric]]
# Fix this test name once we figure out the right one
name = "docker-run-time"
description = "/bin/true cycle time"
# Notionally this test does not have a minimum - smaller is better - but, if we
# get an unexpectedly low number then I think we'd like to know!
minval = 0.5
maxval = 1.5
